apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv-volume2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/your/absolute/path/here"
